### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by burakcan** [BelkaLab/react-yearly-calendar#1]
![screen shot 2015-11-16 at 17 38 45](https://cloud.githubusercontent.com/assets/3121257/11186126/e889328c-8c88-11e5-85e2-e4861ce3a05e.png)

**Comment by GiovanniFrigo** [comment]
I was live-experimenting a few minutes ago, not the greatest idea when you're live on hacker news! Just fixed, thanks for reporting!

**Comment by burakcan** [comment]
:+1:  :)
