### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by JeremyIglehart** [BelkaLab/react-yearly-calendar#20]
I'm getting a React Warning:

`Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see` https://fb.me/prop-types-docs

This is a simple enough fix.

**Comment by rtivital** [comment]
@GiovanniFrigo Are you planning to release update soon that will fix this issue? I can help with pr and fix this issue.

**Comment by GiovanniFrigo** [comment]
This has been sitting for some time in the devel branch, time to publish it!
Fixed this issue in version 1.2.1
