### ISSUE TITLE
Fix weekdays name in Portuguese

### ISSUE THREAD

**Issue by victorpinheiro** [BelkaLab/react-yearly-calendar#35]
Moment.js has some weird behavior with Portuguese dates.
I have sent a PR to fix the function to display the names correctly.

**Comment by victorpinheiro** [comment]
This is the PR: https://github.com/BelkaLab/react-yearly-calendar/pull/33
Can someone please take a look?
Thanks

**Comment by GiovanniFrigo** [comment]
Hello Victor, 

sorry, things have been a bit busy lately. 
Nice catch on this bug! Your fix seems to work fine as well, will merge it now.

Thanks!
