### ISSUE TITLE
Missing Key Properties

### ISSUE THREAD

**Issue by woodenconsulting** [BelkaLab/react-yearly-calendar#8]
Howdy,

Awesome job with this calendar, it's fantastic!

I noticed some missing key props (using React 0.14.7 which throws errors in the console).

https://github.com/BelkaLab/react-yearly-calendar/blob/master/src/Calendar.js#L88
https://github.com/BelkaLab/react-yearly-calendar/blob/master/src/Month.js#L208

![screen shot 2016-03-21 at 4 35 52 pm](https://cloud.githubusercontent.com/assets/4163029/13933329/077c5054-ef83-11e5-812c-104f498d8eb7.png)

I'm about to fix the issue in a fork as I need it cleaned up for what I'm working on. I will open a pull request afterwords if you would like to merge it.

Thanks again for this awesome calendar!

**Comment by Ruzo** [comment]
I dont think this fix made it to NPM.

**Comment by woodenconsulting** [comment]
No it hasn't, I've published a temporary module until it does: https://www.npmjs.com/package/react-yearly-calendar2

**Comment by Ruzo** [comment]
Thanks a lot.

**Comment by GiovanniFrigo** [comment]
My bad, this change was merged but never pushed to npm. 
Updated now (v1.1.3), please switch back to the official package to reduce fragmentation with future releases.

Thanks a lot for reporting this issue @Ruzo !
